/**
 * Test API
 * Test.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    id: string;
    imageUrl: string;
    price: number;
    productType: Product.ProductType;
    name: number;
    myName: Product.MyName;
    title?: string | null;
    description?: string;
    test?: string;
}
export namespace Product {
    export type ProductType = 'product_simple' | 'product_VIP';
    export const ProductType = {
        PRODUCT_SIMPLE: 'product_simple' as ProductType,
        PRODUCT_VIP: 'product_VIP' as ProductType
    };
    export type MyName = 'denis' | 'benjamin';
    export const MyName = {
        DENIS: 'denis' as MyName,
        BENJAMIN: 'benjamin' as MyName
    };
}


