/**
 * Test API
 * Test.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductsSuccessAllOfData } from './productsSuccessAllOfData';


export interface ProductsSuccess { 
    data: ProductsSuccessAllOfData;
    status: string;
}

