/**
 * Test API
 * Test.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductFindOneSuccessAllOfData } from './productFindOneSuccessAllOfData';


export interface ProductFindOneSuccess { 
    data: ProductFindOneSuccessAllOfData;
    status: string;
}

