/**
 * Test API
 * Test.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersSuccessAllOfData } from './usersSuccessAllOfData';


export interface UsersSuccess { 
    data: UsersSuccessAllOfData;
    status: string;
}

