/**
 * Test API
 * Test.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    name: string;
    gender: User.Gender;
    email?: string;
}
export namespace User {
    export type Gender = 'male' | 'female' | 'binary';
    export const Gender = {
        MALE: 'male' as Gender,
        FEMALE: 'female' as Gender,
        BINARY: 'binary' as Gender
    };
}


